### ISSUE TITLE
Error : No such file or directory

### ISSUE THREAD

**Issue by accforgithubtest** [thomas-mauran/chess-tui#50]
Tried to use the docker image, and see this error in the logs.
Are any volume mappings necessary for this to work ?

Am I correct to assume that I will be able to play the game via browser if the container is up and running ? 
I dont see a mention of any ports, so I assume its port 80 by default ?

```
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Error: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
Error: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
Error: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
Error: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```

**Comment by thomas-mauran** [comment]
To play the game using the docker command you need to run the container using -it (interactive TTY) since the docker image only gives an entrypoint to the chess-tui binary, this is why you don't see any port number.
You can pull the image and directly run it using this command `docker run --rm -it ghcr.io/thomas-mauran/chess-tui:main` or build it locally and run it but don't forget -it

**Comment by accforgithubtest** [comment]
Hi! thanks for your reply @thomas-mauran !

Any chances that this will be playable over a browser in the future ? 
The scenario in my mind is to have a self hosted version of the game running a home server accessible over a browser.

**Comment by thomas-mauran** [comment]
> Hi! thanks for your reply @thomas-mauran !
> 
> Any chances that this will be playable over a browser in the future ? The scenario in my mind is to have a self hosted version of the game running a home server accessible over a browser.

Mmmh currently the game is using the library ratatui which doesn't offer a web browser portage to my knowledge, meaning that we would need to rewrite the whole UI part of the game. This will unfortunately not be done since chess-tui is a TUI project (Terminal UI) but the idea of a central game server for 2 clients to connect is good and could be done !

**Comment by accforgithubtest** [comment]
Thanks for the reply !
Makes sense that replacing a UI library central to the application is a lot of work.

Yes my thinking was that would be great to have 2 people play via a self hosted server.

**Comment by accforgithubtest** [comment]
Just came across this project that seems to enable browser access to ratatui.
[I am not a developer, so apologies if my understanding of what I read there is incorrect].

**Comment by thomas-mauran** [comment]
I am closing this issue since the bug might be resolved and creating a new one for the chess-tui over the browser feature you mentionned @accforgithubtest
