### ISSUE TITLE
Material difference

### ISSUE THREAD

**Issue by JeromeSchmied** [thomas-mauran/chess-tui#53]
## Problem

Material difference is not shown.

## Solution

Display material difference in History.

## Additional context

I guess Lichess has support for this too.

**Comment by Inf3n0s** [comment]
Hello, can I try to take this issue ?

**Comment by thomas-mauran** [comment]
> Hello, can I try to take this issue ?

Yes obviously tell me if you are stuck at some point

**Comment by Inf3n0s** [comment]
So , I solved it but I have a issue
![image](https://github.com/user-attachments/assets/a5538bf1-cbf1-424e-8cd9-10716133d140)
The font is small, I saw this crate https://github.com/joshka/tui-big-text, which allow me to make text bigger, if you want it tell me.

I add a new feature which can be optional, I add the functionally to go back with key 'b' which send to the main menu and reset the game, because when I played was annoying to quit the game everytime.
I wait for your response to pull request. 
Thanks in advance!

**Comment by thomas-mauran** [comment]
Hello @Inf3n0s thanks a lot for the contribution I am checking your code right now, for the small font I usually zoom in my terminal using ctrl + to adjust it to the size I want, try to do so in yours to see if it works. The go back to menu feature is a great addition I think it would be useful to have a popup to confirm we want to quit to the menu before doing so to make sure we don't miss click on that button.
